core/urls.py
from django.conf.urls import url

from core.views import UserProfile, EditUserProfile, LoginView, RegistrationView, ActivationView, UploadAvatar, \
    LogoutView, DevView, IdentifyView


urlpatterns = [
    url(r'^$', DevView.as_view(), name="index"),

    url(r'^profile/', UserProfile.as_view(), name='profile'),
    url(r'^edit_profile/', EditUserProfile.as_view(), name='edit_profile'),
    url(r'^change_avatar/$', UploadAvatar),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^reg/$', RegistrationView.as_view(), name='reg'),
    url(r'^activate/$', ActivationView.as_view(), name='activate'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^identify/$', IdentifyView.as_view(), name='identify')
]

geoquiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from geoquiz import settings

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('quiz.urls', namespace='quiz')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from quiz.views import QuestionListView, DetailQuestionView, VoteView, CreateQuestionView, AnswerQuestionView, \
    IndexView, \
    WonderQuestionView, EditQuestionView, DeleteQuestionView, CommentView, QuestionDistributionView, \
    UploadShareImg, AgeStatisticView, GenderStatisticView, PollDateStatisticView, CountriesStatisticView, \
    CitiesStatisticView, GeneralQuestionInfoView, CountryCityView, GetCitySuggests

urlpatterns = [
    url(r'^old/$', IndexView.as_view(), name='index'),
    url(r'^question-list/$', QuestionListView.as_view(), name='question_list'),
    url(r'^question-wonder/$', WonderQuestionView.as_view(), name='next_wonder'),
    url(r'^question-detail/(?P<pk>\d+)/$', DetailQuestionView.as_view(), name='question'),

    url(r'^create-question/$', CreateQuestionView.as_view(), name='create_question'),
    url(r'^edit-question/(?P<pk>\d+)/$', EditQuestionView.as_view(), name='edit_question'),
    url(r'^delete-question/(?P<pk>\d+)/$', DeleteQuestionView.as_view(), name='delete_question'),

    url(r'^answer-question/$', AnswerQuestionView.as_view(), name='answer_question'),

    url(r'^vote-object/$', VoteView.as_view(), name='vote_empty_object'),
    url(r'^vote-object/(?P<object_id>\d+)/(?P<object_type>\d+)/$', VoteView.as_view(), name='vote_object'),
    url(r'^comment-object/(?P<object_id>\d+)/(?P<object_type>\d+)/$', CommentView.as_view(), name='comment_object'),

    url(r'^question-distribution/(?P<quest_id>\d+)/$', QuestionDistributionView.as_view(), name='answers_distribution'),
    url(r'^upload-share-img/$', UploadShareImg.as_view(), name='upload_share_img'),

    url(r'^statistics/age-diagram/(?P<quest_id>\d+)/$', AgeStatisticView.as_view(), name='age_statistic'),
    url(r'^statistics/gender-diagram/(?P<quest_id>\d+)/$', GenderStatisticView.as_view(), name='gender_statistic'),

    url(r'^statistics/poll-date-diagram/(?P<quest_id>\d+)/$', PollDateStatisticView.as_view(),
        name='poll_date_statistic'),

    url(r'^statistics/countries-list/(?P<quest_id>\d+)/$', CountriesStatisticView.as_view(),
        name='countries_list'),

    url(r'^statistics/cities-list/$', CountryCityView.as_view(),
        name='country_cities_list'),

    url(r'^diagrams/statistics/cities-diagram/(?P<quest_id>\d+)/$', CitiesStatisticView.as_view(),
        name='cities_statistic'),

    url(r'^diagrams/statistics/general-info/(?P<quest_id>\d+)/$', GeneralQuestionInfoView.as_view(),
        name='general_info'),

    url(r'^city-suggestions/', GetCitySuggests.as_view(), name='city_suggests')

]

quiz/models.py
from django.db import models
from core.models import User
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist


class Question(models.Model):
    class Meta:
        verbose_name = _('Question')
        verbose_name_plural = _('Questions')

    ALL = 0
    POLITIC = 1
    MEDIA = 2
    EDUCATION = 3
    SPORT = 4
    JOB = 5
    HEALTH = 6
    LIFE = 7
    OTHER = 8

    TOPICS = (
        (POLITIC, _('Politic')),
        (MEDIA, _('Media')),
        (EDUCATION, _('Education')),
        (SPORT, _('Sport')),
        (JOB, _('Job')),
        (HEALTH, _('Health')),
        (LIFE, _('Life')),
        (OTHER, _('Other')),
        (ALL, _('All'))
    )

    author = models.ForeignKey(User)
    title = models.CharField(max_length=100)
    text = models.TextField(blank=True)

    topic = models.PositiveSmallIntegerField(_('Topic'), choices=TOPICS, default=OTHER)

    pub_date = models.DateTimeField(_('Date published'), default=timezone.now)

    rating = models.IntegerField(default=0)
    comments_cnt = models.IntegerField(default=0)
    original_language = models.CharField(max_length=20, default='ru')
    is_active = models.BooleanField(default=True)

    def get_comments_cnt(self):
        return Comment.objects.get_question_comments(self).count()

    def __str__(self):
        return self.title

    def as_dict(self):
        return dict(
                id=self.id,
                author_email=self.author.email,
                author_full_name=self.author.get_full_name(),
                title=self.title,
                text=self.text,
                pub_date=self.pub_date.strftime('%d.%m.%y %H:%M:%S'),
                rating=self.rating,
                original_language=self.original_language,
                comments_cnt=self.get_comments_cnt()
        )

    def get_absolute_url(self):
        return '/'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=200)
    rating = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.text

    def as_dict(self):
        return dict(
                id=self.id,
                question=self.question.text,
                text=self.text,
                rating=self.rating
        )


class Tag(models.Model):
    question = models.ManyToManyField(Question)
    tag = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.tag

    def as_dict(self):
        return dict(
                id=self.id,
                tag=self.tag
        )


class AnswerManager(models.Manager):
    def question_is_answered(self, que, user):
        if not user.is_anonymous():
            answer = self.filter(choice__question=que, is_active=True, user=user).first()
            if answer:
                return answer.is_active
        return None


class Answer(models.Model):
    class Meta:
        unique_together = ('choice', 'user')

    choice = models.ForeignKey(Choice)
    user = models.ForeignKey(User)
    create_date = models.DateTimeField(_('Date answered'), default=timezone.now)
    is_active = models.BooleanField(default=True)

    objects = AnswerManager()

    def __str__(self):
        return str(self.choice.id) + ' : ' + str(self.user.id)

    def as_dict(self):
        return dict(
                id=self.id,
                question=self.question.text,
                create_date=self.create_date.strftime('%d.%m.%y %H:%M:%S'),
                user=self.user.email
        )


class VoteManager(models.Manager):
    @staticmethod
    def get_object(object_id, object_type):
        if object_type == Vote.TYPE_QUESTION:
            return Question.objects.get(id=object_id)
        elif object_type == Vote.TYPE_CHOICE:
            return Choice.objects.get(id=object_id)
        elif object_type == Vote.TYPE_COMMENT:
            return Comment.objects.get(id=object_id)
        else:
            raise ObjectDoesNotExist()

    def get_question_votes(self, question):
        return self.filter(object_id=question.id, object_type=Vote.TYPE_QUESTION, is_active=True).select_related('user')

    def get_choice_votes(self, choice):
        return self.filter(object_id=choice.id, object_type=Vote.TYPE_CHOICE, is_active=True).select_related('user')

    def get_comment_votes(self, comment):
        return self.filter(object_id=comment.id, object_type=Vote.TYPE_COMMENT, is_active=True).select_related('user')

    def question_is_voted(self, que, user):
        if not user.is_anonymous():
            vote = self.filter(object_id=que.id, object_type=Vote.TYPE_QUESTION, is_active=True, user=user).first()
            if vote:
                return vote.is_active
        return None


class Vote(models.Model):
    class Meta:
        """
        Vote == Like
        """
        unique_together = ('object_type', 'object_id', 'user')

    TYPE_QUESTION = 0
    TYPE_CHOICE = 1
    TYPE_COMMENT = 2

    TYPES = (
        (TYPE_QUESTION, _('Vote to question')),
        (TYPE_CHOICE, _('Vote to choice')),
        (TYPE_COMMENT, _('Vote to comment'))
    )

    object_type = models.PositiveIntegerField(choices=TYPES)
    object_id = models.PositiveIntegerField()
    user = models.ForeignKey(User)
    is_active = models.BooleanField(default=True)

    objects = VoteManager()

    def __str__(self):
        return _('Vote from ') + self.user

    def as_dict(self):
        return dict(
                id=self.id,
                object_id=self.object_id,
                object_type=self.object_type,
                value=self.is_active,
                user=self.user.email
        )


class CommentManager(models.Manager):
    @staticmethod
    def get_object(object_id, object_type):
        if object_type == Vote.TYPE_QUESTION:
            return Question.objects.get(id=object_id)
        else:
            raise ObjectDoesNotExist()

    def get_question_comments(self, question):
        return self.filter(object_id=question.id, object_type=Comment.TYPE_QUESTION, is_active=True) \
            .select_related('author')


class Comment(models.Model):
    TYPE_QUESTION = 0

    TYPES = (
        (TYPE_QUESTION, _('Comment to question')),
    )

    object_type = models.PositiveIntegerField(choices=TYPES)
    object_id = models.PositiveIntegerField()
    author = models.ForeignKey(User)
    text = models.TextField()
    is_active = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now)

    objects = CommentManager()

    def __str__(self):
        return _('Comment from ') + self.author

    def as_dict(self):
        return dict(
                id=self.id,
                object_id=self.object_id,
                object_type=self.object_type,
                text=self.text,
                author_name=self.author.get_full_name(),
                pub_date=self.pub_date.strftime('%d.%m.%y %H:%M:%S'),
                author_email=self.author.email,
                author_avatar=self.author.avatar.url,
        )

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        super().save(force_insert=False, force_update=False, using=None,
                     update_fields=None)

        try:
            ENTITIES = [Question]

            type = self.object_type
            entity = ENTITIES[type]

            obj = entity.objects.get(id=self.object_id)
            obj.comments_cnt += 1
            obj.save()

        except (IndexError, ObjectDoesNotExist, AttributeError):
            pass

quiz/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from quiz.models import Question, Choice, Answer, Vote, Comment, Tag

__author__ = 'max'


class CreateQuestionForm(forms.ModelForm):
    def __init__(self, author, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.author = author

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.author = self.author
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Question
        fields = ('title', 'text', 'topic')


class UpdateQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'text', 'topic')


class CreateChoiceForm(forms.ModelForm):
    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.question = question

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.question = self.question
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Choice
        fields = ('text',)


class CreateVoteForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.has_vote = False
        self.vote_id = None

    def clean(self):
        cleaned_data = super().clean()
        object_id = cleaned_data['object_id']
        object_type = cleaned_data['object_type']
        vote = Vote.objects.filter(user=self.user, object_id=object_id, object_type=object_type).first()
        if vote:
            self.has_vote = vote.is_active
            self.vote_id = vote.id
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        if commit:
            if self.has_vote:
                instance.is_active = False
            if self.vote_id:
                instance.id = self.vote_id
            instance.save()
        return instance

    class Meta:
        model = Vote
        fields = ('object_id', 'object_type')


class CreateCommentForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.author = self.user
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Comment
        fields = ('object_id', 'object_type', 'text')


class CreateAnswerForm(forms.ModelForm):
    def __init__(self, choice, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.choice = choice

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        instance.choice = self.choice
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Answer
        fields = ()

quiz/templates/quiz/client/add_choice.html
<div class="form-group">
    <label for="id_choice_<%= choiceId %>" class="col-md-2 control-label">Вариант выбора</label>
    <div class="col-md-5">
        <input id="id_choice_<%= choiceId %>" name="choices" type="text" class="form-control"/>
    </div>
</div>

quiz/templates/quiz/client/add_comment.html
<form action="<%= comment_url %>" method="post" id="add-comment-form">
    {% csrf_token %}
    <div class="form-group">
{#        <label for="id_text">Комментарий</label>#}
        <textarea name="text" id="id_text" rows="4" class="form-control" style="width: 90%;"></textarea>
    </div>
    <div style="clear:both"></div>
    <div style="margin: 20px">
        <button type="submit" class="btn btn-default">Добавить</button>
    </div>
</form>

quiz/templates/quiz/client/comment.html
<div class="comment">
    <div>
        <div class="row">
            <p class="col-md-6">-<%= comment.user %>-</p>
            <p class="pull-right col-md-6"><%= comment.pub_date %></p>
        </div>
    </div>
    <p><%= comment.text %></p>
</div>

quiz/templates/quiz/client/poll_content.html
<% if (typeof(que) !== "undefined") { %>
<div class="poll-content" data-id="<%= que.id %>" data-url="{% url 'quiz:answer_question' %}">
    <div class="poll-question">
        <%= que.title %>
    </div>
    <% for (var I = 0; I < choices.length; I++) { %>
        <div class="poll-option" data-id="<%= choices[I].id %>">
            <%= choices[I].text %>
        </div>
    <% } %>
</div>
<% } else if (error_msg) { %>
<div class="poll-question">
    <p><%= error_msg %></p>
</div>
<% } %>

quiz/templates/quiz/client/question_detail.html
<div class="question-detail-container">
    <div class="header-bar">
        <div class="title-bar">
            <%= renderRate({vote_url: vote_url, que: que, has_voted: has_voted}) %>
            <h1 class="question-detail-title">
                <span style="width:55%; display:inline-block"><%= que.title %></span>
                <ul class="list-unstyled list-inline pull-right que-actions">
                    <li>
                        <a href="#" class="hide-btn hidden-xs">
                            <i class="pe-7s-close"></i>
                            <p>See map</p>
                        </a>
                    </li>
                    <% if (is_author) { %>
                    <li>
                        <a href="#" class="edit-btn hidden-xs" data-id="<%= que.id %>">
                            <i class="pe-7s-edit"></i>
                            <p>Edit</p>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="delete-btn hidden-xs" data-id="<%= que.id %>">
                            <i class="pe-7s-trash"></i>
                            <p>Delete</p>
                        </a>
                    </li>
                    <% } %>
                </ul>
            </h1>
        </div>
    </div>
    <% if (choices.length) { %>
        <fieldset>
            <h4>Выберите ответ:</h4>
            <div>
                <form action="{% url 'quiz:answer_question' %}" method="POST" class="form-horizontal" id="answer-form">
                    {% csrf_token %}
                    <% for (var I = 0; I < choices.length; I++) { %>
                        <div class="">
                            <div class="row">
                                <label for="id_choice_<%= I %>">
                                    <input type="radio" value="<%= choices[I].id %>" name="choice" id="id_choice_<%= I %>" <% if (choices[I].id === choice_answered_id) { %>checked="checked"<% } %>>
                                    <span><%= choices[I].text %></span>
                                </label>
                            </div>
                        </div>
                    <% } %>
                    <br/>
                    {% if user.is_authenticated %}
                        <% if (_.isNull(choice_answered_id)) { %>
                            <button type="submit" class="anim-button big blue" id="answer-btn">Проголосовать</button>
                        <% } else { %>

                        <% } %>
                    {% endif %}
                </form>
            </div>
            <div class="alert alert-success" style="display: none" id="answer-success">Ваш ответ успешно принят!</div>
        </fieldset>
    <% } %>
    <fieldset>
        <div class="answer_content">
            <div class="answer_text">
                <hr>
                <p><%= que.author_full_name %></p>
                <hr>
                <p><%= que.text %></p>
                <% if (tags.length) { %>
                    <hr>
                    <p>
                        <% for (var I = 0; I < tags.length; I++) { %>
                            &#47;
                            <a href="/#tag=<%= tags[I].id %>" data-id="<%= tags[I].id %>" class="search-tag">
                                <%= tags[I].tag %>
                            </a>
                        <% } %>
                    </p>
                <% } %>
                <h4>Комментарии:</h4>
                {% if user.is_authenticated %}
                    {% include 'quiz/client/add_comment.html' %}
                {% endif %}
                <% if (comments.length) { %>
                    <div id="comments">
                        <% for (var I = 0; I < comments.length; I++) { %>
                            <%= renderComment({comment: comments[I]}) %>
                        <% } %>
                    </div>
                <% } else { %>
                    <div id="comments">
                        <p id="while-empty">Пока пусто</p>
                    </div>
                <% } %>
            </div>
        </div>
    </fieldset>
</div>

quiz/templates/quiz/client/question_item.html
<div class="row row-menu">

    <%= renderRate({vote_url: voteUrl, que: que, has_voted: que.has_voted}) %>

    <div class="question-item">
        <a href="#q=<%= que.id %>" data-url="<%= to_details_url %>"><%= que.title %></a>

        <div class="row-fluid question-item-info" style="width: 90%">
            <div class="row-menu-left">
                <p>Комментариев: <%= que.comments_cnt %></p>
            </div>
            <div class="row-menu-right">
                <p>Создан: <%= que.pub_date %></p>
                <!-- здесь иконка страны, откуда автор вопроса-->
            </div>
        </div>
    </div>
</div>

quiz/templates/quiz/client/rate.html
<div class="row rating left" data-url="<%= vote_url %>">
    <div class="rating-wrap rating-wrap-up <% if (has_voted > 0) { %>voted-up<% } else if (has_voted < 0) { %><% } else { %>hovered<% } %>" data-action="1">
        <div class="tri tri-up"></div>
    </div>
    <span class="rating-number"><%= que.rating %></span>

    <div class="rating-wrap rating-wrap-down <% if (has_voted < 0) { %>voted-down<% } else if (has_voted > 0) { %><% } else { %>hovered<% } %>" data-action="-1">
        <div class="tri tri-down"></div>
    </div>
</div>

quiz/templates/quiz/client/share_buttons.html
<span class="share">
    <span class="share__title">Поделиться:</span>
    <span class="share__links">
        <span id="share-data" data-url="<%= url %>" data-title="<%= title %>" data-img="<%= img %>" data-text="<%= text %>"></span>
        <a class="vk-share-link"><i class="icon icon-vk"></i></a>
        <a class="fb-share-link"><i class="icon icon-fcb"></i></a>
        <a class="ok-share-link"><i class="icon icon-ok"></i></a>
        <a class="mailru-share-link"><i class="icon icon-mailru"></i></a>
    </span>
</span>