core/urls.py
from django.conf.urls import url

from core.views import UserProfile, EditUserProfile, LoginView, RegistrationView, ActivationView, UploadAvatar, \
    LogoutView, DevView, IdentifyView


urlpatterns = [
    url(r'^$', DevView.as_view(), name="index"),

    url(r'^profile/', UserProfile.as_view(), name='profile'),
    url(r'^edit_profile/', EditUserProfile.as_view(), name='edit_profile'),
    url(r'^change_avatar/$', UploadAvatar),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^reg/$', RegistrationView.as_view(), name='reg'),
    url(r'^activate/$', ActivationView.as_view(), name='activate'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^identify/$', IdentifyView.as_view(), name='identify')
]

geoquiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from geoquiz import settings

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('quiz.urls', namespace='quiz')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from quiz.views import QuestionListView, DetailQuestionView, VoteView, CreateQuestionView, AnswerQuestionView, \
    IndexView, \
    WonderQuestionView, EditQuestionView, DeleteQuestionView, CommentView, QuestionDistributionView, \
    UploadShareImg, AgeStatisticView, GenderStatisticView, PollDateStatisticView, CountriesStatisticView, \
    CitiesStatisticView, GeneralQuestionInfoView, CountryCityView, GetCitySuggests

urlpatterns = [
    url(r'^old/$', IndexView.as_view(), name='index'),
    url(r'^question-list/$', QuestionListView.as_view(), name='question_list'),
    url(r'^question-wonder/$', WonderQuestionView.as_view(), name='next_wonder'),
    url(r'^question-detail/(?P<pk>\d+)/$', DetailQuestionView.as_view(), name='question'),

    url(r'^create-question/$', CreateQuestionView.as_view(), name='create_question'),
    url(r'^edit-question/(?P<pk>\d+)/$', EditQuestionView.as_view(), name='edit_question'),
    url(r'^delete-question/(?P<pk>\d+)/$', DeleteQuestionView.as_view(), name='delete_question'),

    url(r'^answer-question/$', AnswerQuestionView.as_view(), name='answer_question'),

    url(r'^vote-object/$', VoteView.as_view(), name='vote_empty_object'),
    url(r'^vote-object/(?P<object_id>\d+)/(?P<object_type>\d+)/$', VoteView.as_view(), name='vote_object'),
    url(r'^comment-object/(?P<object_id>\d+)/(?P<object_type>\d+)/$', CommentView.as_view(), name='comment_object'),

    url(r'^question-distribution/(?P<quest_id>\d+)/$', QuestionDistributionView.as_view(), name='answers_distribution'),
    url(r'^upload-share-img/$', UploadShareImg.as_view(), name='upload_share_img'),

    url(r'^statistics/age-diagram/(?P<quest_id>\d+)/$', AgeStatisticView.as_view(), name='age_statistic'),
    url(r'^statistics/gender-diagram/(?P<quest_id>\d+)/$', GenderStatisticView.as_view(), name='gender_statistic'),

    url(r'^statistics/poll-date-diagram/(?P<quest_id>\d+)/$', PollDateStatisticView.as_view(),
        name='poll_date_statistic'),

    url(r'^statistics/countries-list/(?P<quest_id>\d+)/$', CountriesStatisticView.as_view(),
        name='countries_list'),

    url(r'^statistics/cities-list/$', CountryCityView.as_view(),
        name='country_cities_list'),

    url(r'^diagrams/statistics/cities-diagram/(?P<quest_id>\d+)/$', CitiesStatisticView.as_view(),
        name='cities_statistic'),

    url(r'^diagrams/statistics/general-info/(?P<quest_id>\d+)/$', GeneralQuestionInfoView.as_view(),
        name='general_info'),

    url(r'^city-suggestions/', GetCitySuggests.as_view(), name='city_suggests')

]

client/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GeoPoll</title>

    <meta property="og:title" content=""/>
    <meta property="og:image" content="http://{{ request.META.HTTP_HOST }}{% static 'core/img/1455119371_geo_position_pin.png' %}"/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>

    {#  styles  #}
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.1.1/material.indigo-pink.min.css">
    <link rel="stylesheet" href="{% static 'css/libs/material_dev.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/libs/mdl-selectfield.min.css' %}"/>

    {#<link rel="stylesheet" href="{% static 'css/libs/bootstrap.min.css' %}"/>#}
    {#<link rel="stylesheet" href="{% static 'css/libs/bootstrap-datepicker.min.css' %}"/>#}
    <link rel="stylesheet" href="{% static 'css/libs/bootstrap-material-datetimepicker.css' %}"/>
    {#<link rel="stylesheet" href="{% static 'css/libs/bootstrap-tagsinput.css' %}"/> #}

    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/map.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/questions.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/diagram.css' %}"/>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

    <script>
        window.ServerUrls = {
            'answerQuestion': "{% url 'quiz:answer_question' %}",
            'nextWonder': "{% url 'quiz:next_wonder' %}",
            'questionDetail': "/question-detail/",
            'questionList': "{% url 'quiz:question_list' %}",
            'voteObject': "{% url 'quiz:vote_empty_object' %}",
            'profile': "{% url 'core:profile' %}",
            'editProfile': "{% url 'core:edit_profile' %}",
            'login': "{% url 'core:login' %}",
            'logout': "{% url 'core:logout' %}",
            'register': "{% url 'core:reg' %}",
            'identify': "{% url 'core:identify' %}",
            'countries': "statistics/countries-list/",
            'cities': "statistics/cities-list/",
            'createQuestion': "{% url 'quiz:create_question' %}",
            'countrySuggestions': "{% url 'quiz:city_suggests' %}"
        };
    </script>

    <script>
        window.isAuthenticated = {% if user.is_authenticated %}true{% else %}false{% endif %};
        window.availableCountries = JSON.parse('{{ available_countries|safe }}');
        window.shareImage = "http://{{ request.META.HTTP_HOST }}{% static 'core/img/1455119371_geo_position_pin.png' %}";
    </script>

    {% if navigate %}
        <script>
            window.force_navigate = "{{ navigate }}";
        </script>
    {% endif %}

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <div id="regions_div" class="background-map" style="width: 100%; height: 100%;"></div>

        <header class="mdl-layout__header">
            <div class="without-padding mdl-layout__header-row">

                <button class="menu-button mdl-layout--small-screen-only mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="menu">
                    <i class="material-icons">dehaze</i>
                </button>
                <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-left mdl-js-ripple-effect" for="menu">
                    <a href="#" class="js-to-poll return-z-index">
                        <li class="mdl-menu__item">Wonder!</li>
                    </a>
                    <a href="#" class="js-to-hot return-z-index">
                        <li class="mdl-menu__item">Горячее</li>
                    </a>
                    <a href="#" class="js-to-best return-z-index">
                        <li class="mdl-menu__item">Лучшее</li>
                    </a>
                    <a href="#" class="js-to-new return-z-index">
                        <li class="mdl-menu__item">Новое</li>
                    </a>
                </ul>

                <a href="/" class="mdl-layout-title mdl-color-text--accent-contrast">GEOPOLL</a>

                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <div class="js-user-navbar">
                    {% if user.is_authenticated %}
                        {% include 'dj_blocks/user_navbar.html' %}
                    {% else %}
                        {% include 'dj_blocks/anonym_navbar.html' %}
                    {% endif %}
                </div>

            </div>
            <!-- Tabs -->
            <div id="js-tabs" class="tab-bar-norm-height mdl-layout__tab-bar mdl-layout--large-screen-only">
                <a href="#scroll-tab-1" id="poll-tab" class="mdl-layout__tab js-to-poll is-active">Wonder!</a>
                <a href="#scroll-tab-2" id="hot-tab" class="mdl-layout__tab js-to-hot">Горячее</a>
                <a href="#scroll-tab-3" id="best-tab" class="mdl-layout__tab js-to-best">Лучшее</a>
                <a href="#scroll-tab-4" id="new-tab" class="mdl-layout__tab js-to-new">Новое</a>
            </div>
        </header>

        <div class="mdl-layout__content" style="display: none">
            <section class="mdl-layout__tab-panel" id="scroll-tab-1">
                <div class="page-content"></div>
            </section>
            <section class="mdl-layout__tab-panel" id="scroll-tab-2">
                <div class="page-content"></div>
            </section>
            <section class="mdl-layout__tab-panel" id="scroll-tab-3">
                <div class="page-content"></div>
            </section>
            <section class="mdl-layout__tab-panel" id="scroll-tab-4">
                <div class="page-content"></div>
            </section>
        </div>

        <div id="legend"></div>

        <div class="container">
            <div class="questions_popup">
                <div class="contents">

                    <div id="sign-in"></div>
                    <div id="sign-up"></div>
                    <div id="profile"></div>

                    <div id="poll"></div>
                    <div id="question-details"></div>
                    <div id="questions"></div>
                    <div id="create-question"></div>

                    <div id="diagrams"></div>

                    <div id="add-btn">
                        {% if user.is_authenticated %}
                            {% include 'dj_blocks/add_button.html' %}
                        {% endif %}
                    </div>

                    <div class="lower-block"></div>
                </div>
            </div>
            <div id="toast" class="mdl-js-snackbar mdl-snackbar">
                <div class="mdl-snackbar__text"></div>
                <button class="mdl-snackbar__action" type="button"></button>
            </div>
            {% csrf_token %} <!-- For set csrf cookie -->
        </div>

        <div id="chart_div" style="width:400; height:300"></div>
    </div>

    {#  cards  #}
    <script type="text/template" id="sign-in-tml">{% include 'cards/signin_card.html' %}</script>
    <script type="text/template" id="user-navbar-tml">{% include 'bb_blocks/user_navbar.html' %}</script>
    <script type="text/template" id="anonym-navbar-tml">{% include 'dj_blocks/anonym_navbar.html' %}</script>
    <script type="text/template" id="add-button-tml">{% include 'dj_blocks/add_button.html' %}</script>

    <script type="text/template" id="sign-up-tml">{% include 'cards/signup_card.html' %}</script>
    <script type="text/template" id="profile-tml">{% include 'cards/profile_card.html' %}</script>

    <script type="text/template" id="poll-tml">{% include 'cards/poll_card.html' %}</script>
    <script type="text/template" id="question-tml">{% include 'cards/question_card.html' %}</script>
    <script type="text/template" id="comment-tml">{% include 'bb_blocks/comment.html' %}</script>
    <script type="text/template" id="questions-tml">{% include 'cards/question_list_card.html' %}</script>
    <script type="text/template" id="questions-item-tml">{% include 'bb_blocks/question_item.html' %}</script>

    <script type="text/template" id="create-question-tml">{% include 'cards/create_question_card.html' %}</script>
    <script type="text/template" id="add-choice-tml">{% include 'bb_blocks/choice_item.html' %}</script>

    <script type="text/template" id="diagrams-tml">{% include 'cards/diagrams_card.html' %}</script>
    <script type="text/template" id="legend-tml">{% include 'cards/result_map_card.html' %}</script>

    <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
    <script defer data-main="/static/js/main" src="{% static 'js/libs/require.js' %}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.return-z-index').click(function(){
                $('.mdl-layout--fixed-header').css('z-index', 0);
            });
        });
    </script>

<style type="text/css">
    #preload {
        display: block;
        position: fixed;
        z-index: 99999;
        top: 0;left: 0;
        width: 100%;
        height: 100%;
        background: rgb(63,81,181) url({% static 'core/img/circles.svg' %}) center center no-repeat;
        background-size:114px;
    }
</style>
<div id="hellopreloader">
    <div id="preload"></div>
</div>
<script type="text/javascript">
    var preloader = document.getElementById("preload");
    function fadeOutnojquery() {
        preloader.style.opacity = 1;
        var interval = setInterval(function() {
            preloader.style.opacity = preloader.style.opacity - 0.05;
            if (preloader.style.opacity <= 0.05) {
                clearInterval(interval);
                preloader.style.display = "none";
            }
        },16);
    }
    window.onload = function(){
        setTimeout(function() {
            fadeOutnojquery();
        }, 1000);
    };
</script>

</body>
</html>