core/urls.py
from django.conf.urls import url

from core.views import UserProfile, EditUserProfile, LoginView, RegistrationView, ActivationView, UploadAvatar, \
    LogoutView, DevView, IdentifyView


urlpatterns = [
    url(r'^$', DevView.as_view(), name="index"),

    url(r'^profile/', UserProfile.as_view(), name='profile'),
    url(r'^edit_profile/', EditUserProfile.as_view(), name='edit_profile'),
    url(r'^change_avatar/$', UploadAvatar),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^reg/$', RegistrationView.as_view(), name='reg'),
    url(r'^activate/$', ActivationView.as_view(), name='activate'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^identify/$', IdentifyView.as_view(), name='identify')
]

geoquiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from geoquiz import settings

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('quiz.urls', namespace='quiz')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from quiz.views import QuestionListView, DetailQuestionView, VoteView, CreateQuestionView, AnswerQuestionView, \
    IndexView, \
    WonderQuestionView, EditQuestionView, DeleteQuestionView, CommentView, QuestionDistributionView, \
    UploadShareImg, AgeStatisticView, GenderStatisticView, PollDateStatisticView, CountriesStatisticView, \
    CitiesStatisticView, GeneralQuestionInfoView, CountryCityView, GetCitySuggests

urlpatterns = [
    url(r'^old/$', IndexView.as_view(), name='index'),
    url(r'^question-list/$', QuestionListView.as_view(), name='question_list'),
    url(r'^question-wonder/$', WonderQuestionView.as_view(), name='next_wonder'),
    url(r'^question-detail/(?P<pk>\d+)/$', DetailQuestionView.as_view(), name='question'),

    url(r'^create-question/$', CreateQuestionView.as_view(), name='create_question'),
    url(r'^edit-question/(?P<pk>\d+)/$', EditQuestionView.as_view(), name='edit_question'),
    url(r'^delete-question/(?P<pk>\d+)/$', DeleteQuestionView.as_view(), name='delete_question'),

    url(r'^answer-question/$', AnswerQuestionView.as_view(), name='answer_question'),

    url(r'^vote-object/$', VoteView.as_view(), name='vote_empty_object'),
    url(r'^vote-object/(?P<object_id>\d+)/(?P<object_type>\d+)/$', VoteView.as_view(), name='vote_object'),
    url(r'^comment-object/(?P<object_id>\d+)/(?P<object_type>\d+)/$', CommentView.as_view(), name='comment_object'),

    url(r'^question-distribution/(?P<quest_id>\d+)/$', QuestionDistributionView.as_view(), name='answers_distribution'),
    url(r'^upload-share-img/$', UploadShareImg.as_view(), name='upload_share_img'),

    url(r'^statistics/age-diagram/(?P<quest_id>\d+)/$', AgeStatisticView.as_view(), name='age_statistic'),
    url(r'^statistics/gender-diagram/(?P<quest_id>\d+)/$', GenderStatisticView.as_view(), name='gender_statistic'),

    url(r'^statistics/poll-date-diagram/(?P<quest_id>\d+)/$', PollDateStatisticView.as_view(),
        name='poll_date_statistic'),

    url(r'^statistics/countries-list/(?P<quest_id>\d+)/$', CountriesStatisticView.as_view(),
        name='countries_list'),

    url(r'^statistics/cities-list/$', CountryCityView.as_view(),
        name='country_cities_list'),

    url(r'^diagrams/statistics/cities-diagram/(?P<quest_id>\d+)/$', CitiesStatisticView.as_view(),
        name='cities_statistic'),

    url(r'^diagrams/statistics/general-info/(?P<quest_id>\d+)/$', GeneralQuestionInfoView.as_view(),
        name='general_info'),

    url(r'^city-suggestions/', GetCitySuggests.as_view(), name='city_suggests')

]

quiz/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from quiz.models import Question, Choice, Answer, Vote, Comment, Tag

__author__ = 'max'


class CreateQuestionForm(forms.ModelForm):
    def __init__(self, author, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.author = author

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.author = self.author
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Question
        fields = ('title', 'text', 'topic')


class UpdateQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'text', 'topic')


class CreateChoiceForm(forms.ModelForm):
    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.question = question

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.question = self.question
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Choice
        fields = ('text',)


class CreateVoteForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.has_vote = False
        self.vote_id = None

    def clean(self):
        cleaned_data = super().clean()
        object_id = cleaned_data['object_id']
        object_type = cleaned_data['object_type']
        vote = Vote.objects.filter(user=self.user, object_id=object_id, object_type=object_type).first()
        if vote:
            self.has_vote = vote.is_active
            self.vote_id = vote.id
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        if commit:
            if self.has_vote:
                instance.is_active = False
            if self.vote_id:
                instance.id = self.vote_id
            instance.save()
        return instance

    class Meta:
        model = Vote
        fields = ('object_id', 'object_type')


class CreateCommentForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.author = self.user
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Comment
        fields = ('object_id', 'object_type', 'text')


class CreateAnswerForm(forms.ModelForm):
    def __init__(self, choice, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.choice = choice

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.user = self.user
        instance.choice = self.choice
        if commit:
            instance.save()
        return instance

    class Meta:
        model = Answer
        fields = ()

quiz/views.py
from __future__ import division

import json as json_lib
from datetime import datetime
import os
from urllib.parse import unquote

from core.models import User, Country, City
from core.utils import get_country
from django.core.urlresolvers import reverse
from django.db.models import Count, Q
from django.http import HttpResponseBadRequest, HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from geoquiz import settings
from quiz.forms import CreateQuestionForm, CreateChoiceForm, CreateVoteForm, CreateAnswerForm, CreateCommentForm, \
    UpdateQuestionForm
from utils.access import LoginRequiredMixin
from quiz.models import Question, Choice, Vote, Answer, VoteManager, Comment, CommentManager, Tag
from utils.json_views import JsonCreateView, JsonDetailView, JsonListView, JsonUpdateView, JsonDeleteView, JsonView
from math import ceil
from django.core.exceptions import ObjectDoesNotExist
from quiz.utils import prepare_choices_struct, get_percent, random_seq, get_countries_distribution, \
    get_cities_distribution, get_age_statistic, get_gender_statistic, get_poll_date_statistic, get_countries_statistic, \
    get_cities_statistic, get_sharing_text, get_world_statistic
from base64 import b64decode

STANDARD_SHARING_TEXT = 'GeoPoll - Узнай что думают люди в разных уголках земли'


class IndexView(TemplateView):
    http_method_names = ['get']
    template_name = 'quiz/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        context['questions'] = Question.objects.filter(is_active=True) \
            .select_related('author').order_by('-rating')

        context['question_class'] = Question
        context['index'] = True
        return context


class QuestionListView(JsonListView):
    http_method_names = ['get']
    model = Question

    SORTS = {
        1: '-pub_date',
        2: '-rating',
        3: '-comments_cnt',
    }

    GET_MY_QUESTIONS = 1
    GET_MY_ANSWERED_QUESTIONS = 2

    def get(self, request, *args, **kwargs):
        try:
            self.page = int(request.GET.get('page', 1))
            self.question_cnt = int(request.GET.get('questions_cnt', 100))
            self.sort_order = int(request.GET.get('sort', 2))
            self.extra = int(request.GET.get('extra', 0))
        except (ValueError, TypeError):
            self.page = 1
            self.question_cnt = 100
            self.sort_order = 2

        return super().get(request, *args, **kwargs)

    def filter_by_topic(self, questions):
        if 'topic' in self.request.GET:
            try:
                topic_numb = int(self.request.GET['topic'])
                if Question.ALL < topic_numb <= Question.OTHER:
                    return questions.filter(topic=topic_numb)
            except (TypeError, ValueError):
                pass
        return questions

    def filter_by_tags(self, questions):
        if 'tag' in self.request.GET:
            try:
                tag_id = int(self.request.GET['tag'])
                return questions.filter(tag__id__exact=tag_id)
            except (TypeError, ValueError):
                pass
        return questions

    def get_questions(self, start_pos, end_pos):
        sort = self.SORTS.get(self.sort_order, '-rating')
        if self.extra == self.GET_MY_QUESTIONS and not self.request.user.is_anonymous():
            questions = Question.objects.filter(is_active=True, author=self.request.user).select_related(
                    'author').order_by(sort)
        elif self.extra == self.GET_MY_ANSWERED_QUESTIONS and not self.request.user.is_anonymous():
            questions = Question.objects.filter(is_active=True, choice__answer__user=self.request.user).select_related(
                    'author').order_by(sort)
        else:
            questions = Question.objects.filter(is_active=True).select_related('author').order_by(sort)

        questions = self.filter_by_topic(questions)
        questions = self.filter_by_tags(questions)
        questions = questions[start_pos:end_pos]

        data = []
        user = self.request.user
        for que in questions:
            que_data = que.as_dict()
            que_data['has_voted'] = None
            que_data['has_answer'] = None
            que_data['vote_url'] = reverse('quiz:vote_object', args=[que_data['id'], Vote.TYPE_QUESTION])
            if user.is_authenticated():
                que_data['has_voted'] = Vote.objects.question_is_voted(que, user)
                que_data['has_answer'] = Answer.objects.question_is_answered(que, user)
            data.append(que_data)
        return data

    def get_json_data(self, **kwargs):
        end_pos = self.page * self.question_cnt
        start_pos = end_pos - self.question_cnt

        data = dict(page=self.page)
        data['questions'] = self.get_questions(start_pos, end_pos)
        data['pages_cnt'] = ceil(Question.objects.count() / self.question_cnt)

        json = super().get_json_data(**kwargs)
        json['data'] = data
        return json


class WonderQuestionView(JsonDetailView):
    http_method_names = ['get']
    model = Question

    def get_object(self, queryset=None):
        user = self.request.user
        queryset = Question.objects.annotate(num_choices=Count('choice')) \
            .filter(num_choices__gt=0).order_by('?')

        if user.is_anonymous():
            return Question.objects.order_by('?').first()
        else:
            que = queryset.first()
            num_que = len(queryset)
            count = 0
            while Answer.objects.filter(choice__question=que, user=user).exists():
                que = queryset.first()
                if count > num_que:
                    return None
                count += 1
            return que

    def get_choices(self):
        result = []
        choices = Choice.objects.filter(question=self.object, is_active=True)
        for choice in choices:
            choice_data = choice.as_dict()
            result.append(choice_data)
        return result

    def get_json_data(self, **kwargs):
        if self.object is not None:
            json = super().get_json_data(**kwargs)
            json['data'] = self.object.as_dict()
            json['data']['choices'] = self.get_choices()
            json['data']['vote_url'] = reverse('quiz:vote_object', args=[self.object.id, Vote.TYPE_QUESTION])
        else:
            json = super(WonderQuestionView, self).get_error_data(**kwargs)
            json['error'] = "К сожалению, вопросы закончились. Попробуйте позже."
        return json


class DetailQuestionView(JsonDetailView):
    http_method_names = ['get']
    model = Question

    def get_choices(self, user):
        result = []
        choices = Choice.objects.filter(question=self.object, is_active=True)
        for choice in choices:
            choice_data = choice.as_dict()
            if user.is_authenticated():
                choice_data['has_voted'] = Answer.objects.filter(user=user, choice=choice).exists()
            result.append(choice_data)
        return result

    def get_comments(self):
        comments = Comment.objects.get_question_comments(self.object).order_by('-pub_date')
        return self.objects_to_dict(comments)

    def get_json_data(self, **kwargs):
        user = self.request.user

        data = dict(que=self.object.as_dict())
        data['que']['choices'] = self.get_choices(user)
        data['que']['comments'] = self.get_comments()
        data['que']['tags'] = self.objects_to_dict(self.object.tag_set.all())
        data['que']['is_author'] = user == self.object.author
        data['que']['is_anonymous'] = user.is_anonymous()
        data['que']['current_user_avatar'] = ''
        if not user.is_anonymous():
            data['que']['current_user_avatar'] = user.avatar.url

        data['que']['has_voted'] = None
        data['que']['choice_answered_id'] = None
        data['que']['choice_answered_text'] = None

        if user.is_authenticated():
            answer = Answer.objects.filter(choice__question=self.object, user=user, is_active=True).first()
            if answer is not None:
                data['que']['choice_answered_id'] = answer.choice.id
                data['que']['choice_answered_text'] = answer.choice.text
            data['que']['has_voted'] = Vote.objects.question_is_voted(self.object, self.request.user)

        data['que']['vote_url'] = reverse('quiz:vote_object', args=[self.object.id, Vote.TYPE_QUESTION])
        data['que']['comment_url'] = reverse('quiz:comment_object', args=[self.object.id, Comment.TYPE_QUESTION])

        json = super().get_json_data(**kwargs)
        json['data'] = data
        return json


class VoteView(LoginRequiredMixin, JsonCreateView):
    http_method_names = ['post']
    model = Vote
    form_class = CreateVoteForm
    success_url = None

    def post(self, request, *args, **kwargs):

        object_id = kwargs.get('object_id')
        object_type = kwargs.get('object_type')

        if not object_id or not object_type:
            return HttpResponseBadRequest()

        try:
            self.object_id = int(object_id)
            self.object_type = int(object_type)
            self.voted_object = VoteManager.get_object(self.object_id, self.object_type)
        except (ValueError, ObjectDoesNotExist):
            return HttpResponseBadRequest()
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['data'] = {
            'object_id': self.object_id,
            'object_type': self.object_type,
        }
        return kwargs

    def form_valid(self, form):

        if not form.has_vote:
            self.voted_object.rating += 1
            self.is_increace = True
        else:
            self.voted_object.rating -= 1

quiz/templates/quiz/create_question.html
{% extends 'core/base.html' %}
{% load static %}
{% load form_tags %}

{% block regions_map %}{% endblock %}

{% block content %}
    <div class="row">
        <h3 class="col-md-offset-1">Создать опрос</h3>
    </div>
    <br/>
    <form action="{% if update %}{% url 'quiz:edit_question' object.id %}{% else %}{% url 'quiz:create_question' %}{% endif %}" method="post" class="form-horizontal" id="create-que-form">
        {% csrf_token %}

        {% for field in form %}
            <div class="alerts">
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
            {% endfor %}
            </div>
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-md-2 control-label">{{ field.label }}</label>
                <div class="col-md-5">
                    {{ field|add_class }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <label class="col-md-2 control-label">Tags</label>
            <div class="col-md-5">
                <input type="text" name="tags" class="form-control" value="{% if update %}{% if instance_tags %}{{ instance_tags }}{% endif %}{% else %}all{% endif %}" data-role="tagsinput"/>
            </div>
        </div>

        <hr/>
        <button class="btn btn-default col-md-offset-2" id="js-add-choice" data-last-id="0">Добавить ответ</button>
        <div id="choices" style="margin-top:20px">
            {% if instance_choices %}
                {% for choice in instance_choices %}
                    <div class="form-group">
                        <label for="id_choice_{{ choice.id }}" class="col-md-2 control-label">Вариант выбора</label>
                        <div class="col-md-5">
                            <input id="id_choice_{{ choice.id }}" name="old_choices" type="text" class="form-control" value="{{ choice.text }}"/>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <hr/>

        <br/>
        <button type="submit" class="btn btn-submit btn-lg col-md-offset-1">Отправить</button>
    </form>
{% endblock %}

{% block templates %}
    <script type="text/template" id="choice-tml">
        {% include 'quiz/client/add_choice.html' %}
    </script>
{% endblock %}

{% block js %}
    <script src="{% static 'quiz/js/functions/question.js' %}"></script>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'core/base.html' %}
{% load static %}
{% load form_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static 'quiz/css/index.css' %}"/>
    <link rel="stylesheet" href="{% static 'quiz/css/radio-button.css' %}"/>
    <link rel="stylesheet" href="{% static 'quiz/css/buttons.css' %}"/>
    <link rel="stylesheet" href="{% static 'quiz/css/loader.css' %}"/>
    <link rel="stylesheet" href="{% static 'core/css/icomoon.css' %}"/>
    <link rel="stylesheet" href="{% static 'quiz/css/share.css' %}"/>
{% endblock %}

{% block meta %}
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:site_name" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:description" content=""/>
{% endblock %}

{% block content %}
    <div id="anonym-alert" class="alert alert-info hide-content">
        Ваши ответы не учитываются, т.к. вы не авторизованы. После авторизации все ваши ответы засчитаются.
    </div>

    <div class="">
    <div class="questions_popup">

        <div class="content-wrap">
{#            <ul class="nav nav-tabs">#}
{#                <li class="active"><a href="#wonder" target=".wonder" data-toggle="tab">Wonder</a></li>#}
{#                <li><a href="#hot" target=".questions" data-toggle="tab">Hot List</a></li>#}
{#                <li><a href="#best" target=".questions" data-toggle="tab">Best List</a></li>#}
{#                <li><a href="#new" target=".questions" data-toggle="tab">New List</a></li>#}
{#            </ul>#}

            <div class="contents">
                <form class="wonder hide-content">
                    <div class="poll-wrapper" data-url="{% url 'quiz:next_wonder' %}">
                        <div id="js-wonder-question-container" class="poll_question"
                             distribution-url="{% url 'quiz:answers_distribution' 1 %}">
                            <!-- TODO ADD WONDER QUESTION ID -->
                        </div>
                        <div class="poll-place"></div>
                        <div class="loader hide-content">
                            <div class="small1">
                                <div class="small3 ball smallball1"></div>
                                <div class="small3 ball smallball2"></div>
                                <div class="small3 ball smallball3"></div>
                                <div class="small3 ball smallball4"></div>
                            </div>
                            <div class="small2">
                                <div class="small3 ball smallball5"></div>
                                <div class="small3 ball smallball6"></div>
                                <div class="small3 ball smallball7"></div>
                                <div class="small3 ball smallball8"></div>
                            </div>
                            <div class="bigcon">
                                <div class="big2 ball"></div>
                            </div>
                        </div>
                    </div>
                    </br>
                    <center>
                        <button type="button" class="anim-button big blue" id="skip-question">Пропустить</button>
                    </center>
                </form>

                <div class="row questions hide-content">
                    <select id="js-id-topic-filter" class="row-menu">
                        {% for topic in question_class.TOPICS %}
                            <option id="topic-id-{{ topic|index:0 }}"
                                    class="js-filter-topic"
                                    url="{% url 'quiz:question_list' %}?topic={{ topic|index:0 }}"
                                    name="topic-name"
                                    {% if topic|index:0 == current_topic %}
                                    selected
                                    {% elif not current_topic and topic|index:0 == question_class.ALL %}
                                    selected
                                    {% endif %}
                                    >{{ topic|index:1 }}</option>
                        {% endfor %}
                    </select>

                    <div class="questions-list" data-url="{% url 'quiz:question_list' %}"></div>
                    <img src="{% static 'quiz/img/Professortocat_v2.png' %}" class="catty hide-content" width="200" height="200" alt=""/>
                </div>

                <div class="question-detail hide-content"></div>
            </div>
        </div>
    </div>
    <div class="lower-block hide-content">
        <div class="lower-block-left">
            <button type="button" class="btn btn-info" id="comments-question">Комментарии</button>
            <button type="button" class="btn btn-info" id="statistics-question">Статистика</button>
        </div>
        <button type="button" class="anim-button big blue" id="next-question">Следующий</button>
        <button type="button" class="anim-button big blue" id="see-question" style="display:none">К вопросу</button>
    </div>
{% endblock %}

{% block templates %}
    <script type="text/template" id="rate-tml">
        {% include 'quiz/client/rate.html' %}
    </script>
    <script type="text/template" id="question-tml">
        {% include 'quiz/client/question_detail.html' %}
    </script>
    <script type="text/template" id="comment-tml">
        {% include 'quiz/client/comment.html' %}
    </script>
    <script type="text/template" id="question-item-tml">
        {% include 'quiz/client/question_item.html' %}
    </script>
    <script type="text/template" id="poll-tml">
        {% include 'quiz/client/poll_content.html' %}
    </script>
    <script type="text/template" id="share-btn-tml">
        {% include 'quiz/client/share_buttons.html' %}
    </script>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="{% static 'quiz/js/initialize_map.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyDlA_CCrKpAyGq9P3NNVNMQxWSrIVe1awk&sensor=false&callback=initMap"></script>
    <script defer type="text/javascript" src="{% static 'quiz/js/markerwithlabel.js' %}"></script>

    <script src="{% static 'quiz/js/functions/answer.js' %}"></script>
    <script src="{% static 'quiz/js/functions/comment.js' %}"></script>
    <script src="{% static 'quiz/js/functions/poll.js' %}"></script>
    <script src="{% static 'quiz/js/functions/question.js' %}"></script>
    <script src="{% static 'quiz/js/functions/vote.js' %}"></script>
    {% block functions %}{% endblock %}

    <script src="{% static 'quiz/js/render/poll.js' %}"></script>
    <script src="{% static 'quiz/js/render/question.js' %}"></script>
    <script src="{% static 'quiz/js/render/question_list.js' %}"></script>
    {% block render %}{% endblock %}

    <script src="{% static 'quiz/js/index.js' %}"></script>

    <script src="{% static 'quiz/js/route/index.js' %}"></script>
    <script src="{% static 'quiz/js/route/question.js' %}"></script>
    {% block route %}{% endblock %}

    <script src="{% static 'quiz/js/functions/share.js' %}"></script>

    <script>
        $(document).ready(function () {
            var timer = setInterval(function () {
                var item = $('div[controlheight="33"]');
                if (item.length > 0) {
                    item.css('display', 'none');
                    clearInterval(timer);
                }
            }, 100);
        });
    </script>

{% endblock %}

quiz/templates/quiz/statistics.htm
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Highcharts Example</title>

		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<style type="text/css">
${demo.css}
		</style>
	</head>
	<body>

<script src="../../static/quiz/js/diagrams/highstock.js"></script>
<script src="../../static/quiz/js/diagrams/exporting.js"></script>
<script src="../../static/quiz/js/diagrams/diagram-utils.js"></script>
<script src="../../static/quiz/js/diagrams/gender-diagram.js"></script>
<script src="../../static/quiz/js/diagrams/age-diagram.js"></script>
<script src="../../static/quiz/js/diagrams/date-diagram.js"></script>
<div id="gender-diagram" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="age-diagram" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="date-diagram" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

	</body>
</html>